name: Test and Auto Create Pull Request

on:
  push:
    branches-ignore:
      - main

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm run test -- --ci --maxWorkers=2

      - name: Build Project (Validation)
        run: npm run build -- --configuration production

  create-pr:
    name: Create PR to main
    needs: unit-tests
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_EXISTS=$(gh pr list --head "${GITHUB_REF_NAME}" --base main --json url --jq 'length')

          if [ "$PR_EXISTS" -eq "0" ]; then
            gh pr create \
              --base main \
              --head "${GITHUB_REF_NAME}" \
              --title "Automated PR: ${GITHUB_REF_NAME}" \
              --body "Este Pull Request foi validado e criado automaticamente após testes bem-sucedidos na branch **${GITHUB_REF_NAME}**."
            echo "Pull Request criado com sucesso!"
          else
            echo "Já existe um Pull Request aberto para a branch ${GITHUB_REF_NAME}."
          fi
